# Generated by Django 3.1.3 on 2020-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201208_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='eje', max_length=100),
        ),
    ]
